AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"
    - "tmp/**/*"

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

Naming/MethodName:
  Exclude:
    - "lib/frequency.rb"   # __run, __coerce, etc. are intentionally underscored

Style/AccessModifierDeclarations:
  Enabled: false
Style/ClassMethodsDefinitions:
  Enabled: false
Style/SingleLineMethods:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
